### PR TITLE
Fix false positive test results

### PR DESCRIPTION
**Pull request by YozhikVolkoff**
The problem is that the test-run/test-run.py script returns exit code 0
in case of using '-j -1' option stated in test-run/CMakeLists.txt even
though some tests were failed during running testing workflow.

Updates test-run submodule, loads necessary patch.

Test-run patch: https://github.com/tarantool/test-run/commit/c3450036

### CODE REVIEW

**Comment by Totktonada** [comment]
The update is okay. Several wording nits:

> The problem is that the test-run/test-run.py script returns exit code 0
> in case of using '-j -1' option stated in test-run/CMakeLists.txt even
> though some tests were failed during running OS X testing workflow.

It may confuse a reader: like the problem is specific for Mac OS. I would not mention Mac OS here at all or move description how you meet the problem out of the change description.

> Fetches fixing test-run patch in tarantool-c repository from
> tarantool/test-run.

It seems, here we have a grammar problem. Please, reword it in some simple way. You can call the change 'test-run submodule update' and I guess it will be clear enough for all readers.

Please, update commit and PR description.

**Comment by YozhikVolkoff** [comment]
I've updated PR description and commit

**Review by Totktonada — APPROVED** [review]
LGTM.

**Review by Korablev77 — APPROVED** [review]
LGTM as well

**Pull request merged**
